# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version=1.21.9
minecraft_version_range=[1.21.9,1.22)


# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.17.2
fabric_version=0.133.14+1.21.9
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=3.0.3
maven_group=de.crafty.eiv
mod_id=eiv
mod_license=MIT
mod_name=Extended ItemView
mod_description=A mod all around simplifying your life by showing you the recipes you need! :D

# Forge Properties
forge_version=58.1.0
forge_version_range=[58.1.0,)
forge_loader_version_range=[58,)
forge_loader_version=[58,)

# NeoForge Properties
neoforge_version=21.9.2-beta
neoforge_version_range=[21.9,)
neoforge_loader_version_range=[1,)

mod_authors=2Bad4Mods